Fix NPE caused by getCursorCachedLight
fix :
```
[08:09:58] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Exception ticking world
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:2731) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:3073) ~[MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111) ~[bsx.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:2830) ~[MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:750) [?:1.8.0_402]
Caused by: java.lang.NullPointerException
	at org.embeddedt.archaicfix.lighting.world.lighting.LightingEngine.getCursorCachedLight(LightingEngine.java:391) ~[LightingEngine.class:?]
	at org.embeddedt.archaicfix.lighting.world.lighting.LightingEngine.processQueuedBrightening(LightingEngine.java:245) ~[LightingEngine.class:?]
	at org.embeddedt.archaicfix.lighting.world.lighting.LightingEngine.iterateThroughQueuedUpdates(LightingEngine.java:198) ~[LightingEngine.class:?]
	at org.embeddedt.archaicfix.lighting.world.lighting.LightingEngine.processLightUpdatesForTypeInner(LightingEngine.java:119) ~[LightingEngine.class:?]
	at org.embeddedt.archaicfix.lighting.world.lighting.LightingEngine.processLightUpdatesForType(LightingEngine.java:103) ~[LightingEngine.class:?]
	at org.embeddedt.archaicfix.lighting.world.lighting.LightingEngine.processLightUpdates(LightingEngine.java:93) ~[LightingEngine.class:?]
	at net.minecraft.world.chunk.Chunk.handler$zon000$archaicfix$onGetLightSubtracted(Chunk.java:2614) ~[apx.class:?]
	at net.minecraft.world.chunk.Chunk.func_76629_c(Chunk.java) ~[apx.class:?]
	at net.minecraft.world.World.optimizationsAndTweaks$getChunkBlockLightValue(World.java:51912) ~[ahb.class:?]
	at net.minecraft.world.World.func_72849_a(World.java:51869) ~[ahb.class:?]
	at net.minecraft.world.World.func_72957_l(World.java:764) ~[ahb.class:?]
	at net.minecraft.block.BlockGrass.handler$zhk001$updateTick(BlockGrass.java:1029) ~[alh.class:?]
	at net.minecraft.block.BlockGrass.func_149674_a(BlockGrass.java) ~[alh.class:?]
	at net.minecraft.world.WorldServer.optimizationsAndTweaks$handleBlockTick(WorldServer.java:1480) ~[mt.class:?]
	at net.minecraft.world.WorldServer.optimizationsAndTweaks$handleBlockTicks(WorldServer.java:1463) ~[mt.class:?]
	at net.minecraft.world.WorldServer.processChunk(WorldServer.java:1402) ~[mt.class:?]
	at net.minecraft.world.WorldServer.func_147456_g(WorldServer.java:1391) ~[mt.class:?]
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:183) ~[mt.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:2727) ~[MinecraftServer.class:?]
	... 4 more
```